### ISSUE TITLE
problem in test

### ISSUE THREAD

**Issue by sdp369** [metobom/prepare-data-for-UNet#3]
Thank you very much for this code
there is no problem in training using my own dataset
but I cannot test images to generate the prediction :

Epoch 00001: loss improved from inf to 0.10034, saving model to unet_membrane.hdf5

1/20 [>.............................] - ETA: 48s
2/20 [==>...........................] - ETA: 23s
3/20 [===>..........................] - ETA: 15sTraceback (most recent call last):
File "F:/unet-master/main.py", line 21, in 
results = model.predict_generator(testGene,20,verbose=1,max_queue_size=1)
File "D:\Anaconda3\envs\py36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 1530, in predict_generator
verbose=verbose)
File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training_generator.py", line 417, in predict_generator
generator_output = next(output_generator)
File "D:\Anaconda3\envs\py36\lib\site-packages\keras\utils\data_utils.py", line 785, in get
raise StopIteration()
StopIteration

please help

**Comment by metobom** [comment]
How many test images do you have?

**Comment by sdp369** [comment]
> 您有多少张测试图像？

only three

**Comment by metobom** [comment]
Try changing 20 to 3 in 'results = model.predict_generator(testGene,20,verbose=1,max_queue_size=1)'

**Comment by sdp369** [comment]
> Try changing 20 to 3 in 'results = model.predict_generator(testGene,20,verbose=1,max_queue_size=1)'

Thank you! It works.
But I have a new issue:

F:\自带浏览器下载\unet-master\data.py:125: UserWarning: C:/Users/sdp/Desktop/images\2_predict.png is a low contrast image
  io.imsave(os.path.join(save_path,"%d_predict.png"%i),img)
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

When I convert image to uint8 using img_as_ubyte, it shows:

F:\自带浏览器下载\unet-master\data.py:125: UserWarning: C:/Users/sdp/Desktop/images\2_predict.png is a low contrast image
  io.imsave(os.path.join(save_path,"%d_predict.png"%i),img_as_ubyte(img))

**Comment by metobom** [comment]
I had that too. I solved by increasing contrast of my images. You can use prepocess.py for that.

**Comment by sdp369** [comment]
> I had that too. I solved by increasing contrast of my images. You can use prepocess.py for that.

 Using prepocess.py, I get some distorted images, and the issue still  exists.

**Comment by metobom** [comment]
Try commenting conv10 layer which has sigmoid as activation and train again.
